services:
  3x-ui:
    image: ${XUI_IMAGE:-ghcr.io/mhsanaei/3x-ui:v2.8.9}
    container_name: 3x-ui
    restart: unless-stopped
    networks:
      - xui-network
    expose:
      - "2053"
      - "443"
      - "80"
    volumes:
      - ./data:/etc/x-ui
      - ${SSL_CERTS_PATH}:/root/cert:ro

  nginx:
    image: ${NGINX_IMAGE:-nginx:alpine}
    container_name: nginx
    restart: unless-stopped
    networks:
      - xui-network
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ${SSL_CERTS_PATH}:/root/cert:ro
    depends_on:
      - 3x-ui

networks:
  xui-network:
    driver: bridge
